### ISSUE TITLE
Hydra？

### ISSUE THREAD

**Issue by Ystartff** [DeepMed-Lab-ECNU/FS_MedSAM2#2]
What is the version of your virtual environment?

**Comment by byhwhite** [comment]
python 3.10, follow the SAM2 official repo to create the environment.

**Comment by Ystartff** [comment]
using device: cuda
Traceback (most recent call last):
  File "/mnt/data/linda/yyf/FS_MedSAM2-main/notebooks/infer_fsmedsam2_by_slice.py", line 80, in <module>
    predictor = build_fsmedsam2_video_predictor(model_cfg, sam2_checkpoint, device=device)
  File "/mnt/data/linda/yyf/FS_MedSAM2-main/notebooks/sam2/build_fsmedsam2.py", line 108, in build_fsmedsam2_video_predictor
    cfg = compose(config_name=config_file, overrides=hydra_overrides)
  File "/home/linda/anaconda3/envs/sam2/lib/python3.10/site-packages/hydra/compose.py", line 32, in compose
    assert (
AssertionError: GlobalHydra is not initialized, use @hydra.main() or call one of the hydra initialization methods first
